FROM mongo:latest

ADD restaurants.json /var/log/restaurants.json
ADD import_data.sh /home/import_data.sh

#RUN mongoimport --db zomato --collection restaurants --drop --file /var/log/restaurants.json

